// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: pkg/events.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_left  Direction = 0
	Direction_right Direction = 1
	Direction_up    Direction = 2
	Direction_down  Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "left",
		1: "right",
		2: "up",
		3: "down",
	}
	Direction_value = map[string]int32{
		"left":  0,
		"right": 1,
		"up":    2,
		"down":  3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_events_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_pkg_events_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{0}
}

type Event_Type int32

const (
	Event_type_init       Event_Type = 0
	Event_type_connect    Event_Type = 1
	Event_type_exit       Event_Type = 2
	Event_type_idle       Event_Type = 3
	Event_type_move       Event_Type = 4
	Event_type_empty      Event_Type = 5
	Event_type_teleport   Event_Type = 6
	Event_type_updateinfo Event_Type = 7
)

// Enum value maps for Event_Type.
var (
	Event_Type_name = map[int32]string{
		0: "type_init",
		1: "type_connect",
		2: "type_exit",
		3: "type_idle",
		4: "type_move",
		5: "type_empty",
		6: "type_teleport",
		7: "type_updateinfo",
	}
	Event_Type_value = map[string]int32{
		"type_init":       0,
		"type_connect":    1,
		"type_exit":       2,
		"type_idle":       3,
		"type_move":       4,
		"type_empty":      5,
		"type_teleport":   6,
		"type_updateinfo": 7,
	}
)

func (x Event_Type) Enum() *Event_Type {
	p := new(Event_Type)
	*p = x
	return p
}

func (x Event_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_events_proto_enumTypes[1].Descriptor()
}

func (Event_Type) Type() protoreflect.EnumType {
	return &file_pkg_events_proto_enumTypes[1]
}

func (x Event_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Type.Descriptor instead.
func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{3, 0}
}

type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X     float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y     float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Level string  `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{0}
}

func (x *Pos) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Pos) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type Unit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pos       *Pos      `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Frame     int32     `protobuf:"varint,3,opt,name=frame,proto3" json:"frame,omitempty"`
	Skin      string    `protobuf:"bytes,4,opt,name=skin,proto3" json:"skin,omitempty"`
	Action    string    `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Speed     float64   `protobuf:"fixed64,6,opt,name=speed,proto3" json:"speed,omitempty"`
	Direction Direction `protobuf:"varint,7,opt,name=direction,proto3,enum=pkg.Direction" json:"direction,omitempty"`
	Side      Direction `protobuf:"varint,8,opt,name=side,proto3,enum=pkg.Direction" json:"side,omitempty"`
	Info      *CharInfo `protobuf:"bytes,9,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *Unit) Reset() {
	*x = Unit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{1}
}

func (x *Unit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Unit) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Unit) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *Unit) GetSkin() string {
	if x != nil {
		return x.Skin
	}
	return ""
}

func (x *Unit) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Unit) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Unit) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_left
}

func (x *Unit) GetSide() Direction {
	if x != nil {
		return x.Side
	}
	return Direction_left
}

func (x *Unit) GetInfo() *CharInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CharInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxHealth     int64 `protobuf:"varint,1,opt,name=MaxHealth,proto3" json:"MaxHealth,omitempty"`
	CurrentHealth int64 `protobuf:"varint,2,opt,name=CurrentHealth,proto3" json:"CurrentHealth,omitempty"`
}

func (x *CharInfo) Reset() {
	*x = CharInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharInfo) ProtoMessage() {}

func (x *CharInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharInfo.ProtoReflect.Descriptor instead.
func (*CharInfo) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{2}
}

func (x *CharInfo) GetMaxHealth() int64 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *CharInfo) GetCurrentHealth() int64 {
	if x != nil {
		return x.CurrentHealth
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Event_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pkg.Event_Type" json:"type,omitempty"`
	// Types that are assignable to Data:
	//
	//	*Event_Init
	//	*Event_Connect
	//	*Event_Exit
	//	*Event_Idle
	//	*Event_Move
	//	*Event_Teleport
	//	*Event_UpdateInfo
	Data isEvent_Data `protobuf_oneof:"data"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetType() Event_Type {
	if x != nil {
		return x.Type
	}
	return Event_type_init
}

func (m *Event) GetData() isEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Event) GetInit() *EventInit {
	if x, ok := x.GetData().(*Event_Init); ok {
		return x.Init
	}
	return nil
}

func (x *Event) GetConnect() *EventConnect {
	if x, ok := x.GetData().(*Event_Connect); ok {
		return x.Connect
	}
	return nil
}

func (x *Event) GetExit() *EventExit {
	if x, ok := x.GetData().(*Event_Exit); ok {
		return x.Exit
	}
	return nil
}

func (x *Event) GetIdle() *EventIdle {
	if x, ok := x.GetData().(*Event_Idle); ok {
		return x.Idle
	}
	return nil
}

func (x *Event) GetMove() *EventMove {
	if x, ok := x.GetData().(*Event_Move); ok {
		return x.Move
	}
	return nil
}

func (x *Event) GetTeleport() *EventTeleport {
	if x, ok := x.GetData().(*Event_Teleport); ok {
		return x.Teleport
	}
	return nil
}

func (x *Event) GetUpdateInfo() *UpdateInfo {
	if x, ok := x.GetData().(*Event_UpdateInfo); ok {
		return x.UpdateInfo
	}
	return nil
}

type isEvent_Data interface {
	isEvent_Data()
}

type Event_Init struct {
	Init *EventInit `protobuf:"bytes,2,opt,name=init,proto3,oneof"`
}

type Event_Connect struct {
	Connect *EventConnect `protobuf:"bytes,3,opt,name=connect,proto3,oneof"`
}

type Event_Exit struct {
	Exit *EventExit `protobuf:"bytes,4,opt,name=exit,proto3,oneof"`
}

type Event_Idle struct {
	Idle *EventIdle `protobuf:"bytes,5,opt,name=idle,proto3,oneof"`
}

type Event_Move struct {
	Move *EventMove `protobuf:"bytes,6,opt,name=move,proto3,oneof"`
}

type Event_Teleport struct {
	Teleport *EventTeleport `protobuf:"bytes,7,opt,name=teleport,proto3,oneof"`
}

type Event_UpdateInfo struct {
	UpdateInfo *UpdateInfo `protobuf:"bytes,8,opt,name=updateInfo,proto3,oneof"`
}

func (*Event_Init) isEvent_Data() {}

func (*Event_Connect) isEvent_Data() {}

func (*Event_Exit) isEvent_Data() {}

func (*Event_Idle) isEvent_Data() {}

func (*Event_Move) isEvent_Data() {}

func (*Event_Teleport) isEvent_Data() {}

func (*Event_UpdateInfo) isEvent_Data() {}

type UpdateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId string    `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Info   *CharInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *UpdateInfo) Reset() {
	*x = UpdateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfo) ProtoMessage() {}

func (x *UpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfo.ProtoReflect.Descriptor instead.
func (*UpdateInfo) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateInfo) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UpdateInfo) GetInfo() *CharInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type EventInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string           `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Units    map[string]*Unit `protobuf:"bytes,2,rep,name=units,proto3" json:"units,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *EventInit) Reset() {
	*x = EventInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInit) ProtoMessage() {}

func (x *EventInit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInit.ProtoReflect.Descriptor instead.
func (*EventInit) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{5}
}

func (x *EventInit) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *EventInit) GetUnits() map[string]*Unit {
	if x != nil {
		return x.Units
	}
	return nil
}

type EventConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit *Unit `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *EventConnect) Reset() {
	*x = EventConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventConnect) ProtoMessage() {}

func (x *EventConnect) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventConnect.ProtoReflect.Descriptor instead.
func (*EventConnect) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{6}
}

func (x *EventConnect) GetUnit() *Unit {
	if x != nil {
		return x.Unit
	}
	return nil
}

type EventTeleport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Pos      *Pos   `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *EventTeleport) Reset() {
	*x = EventTeleport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventTeleport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTeleport) ProtoMessage() {}

func (x *EventTeleport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTeleport.ProtoReflect.Descriptor instead.
func (*EventTeleport) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{7}
}

func (x *EventTeleport) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *EventTeleport) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

type EventExit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *EventExit) Reset() {
	*x = EventExit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventExit) ProtoMessage() {}

func (x *EventExit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventExit.ProtoReflect.Descriptor instead.
func (*EventExit) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{8}
}

func (x *EventExit) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type EventIdle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *EventIdle) Reset() {
	*x = EventIdle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventIdle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventIdle) ProtoMessage() {}

func (x *EventIdle) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventIdle.ProtoReflect.Descriptor instead.
func (*EventIdle) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{9}
}

func (x *EventIdle) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type EventMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId  string    `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Direction Direction `protobuf:"varint,2,opt,name=direction,proto3,enum=pkg.Direction" json:"direction,omitempty"`
}

func (x *EventMove) Reset() {
	*x = EventMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_events_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMove) ProtoMessage() {}

func (x *EventMove) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMove.ProtoReflect.Descriptor instead.
func (*EventMove) Descriptor() ([]byte, []int) {
	return file_pkg_events_proto_rawDescGZIP(), []int{10}
}

func (x *EventMove) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *EventMove) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_left
}

var File_pkg_events_proto protoreflect.FileDescriptor

var file_pkg_events_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x70, 0x6b, 0x67, 0x22, 0x37, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x22, 0xff, 0x01, 0x0a, 0x04, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x03, 0x70, 0x6f, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x50, 0x6f, 0x73,
	0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6b, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x2c, 0x0a,
	0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x73,
	0x69, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x6b, 0x67, 0x2e,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12,
	0x21, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x6b, 0x67, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x22, 0x4e, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x4d, 0x61, 0x78, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x4d, 0x61, 0x78, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x24, 0x0a, 0x0d,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x22, 0xef, 0x03, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6b, 0x67,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x24, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x48,
	0x00, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x65, 0x78, 0x69, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x45, 0x78, 0x69, 0x74, 0x48, 0x00, 0x52, 0x04, 0x65, 0x78, 0x69, 0x74, 0x12, 0x24, 0x0a, 0x04,
	0x69, 0x64, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6b, 0x67,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x69, 0x64,
	0x6c, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x76, 0x65,
	0x48, 0x00, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x74, 0x65, 0x6c, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6b, 0x67,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x00,
	0x52, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48,
	0x00, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x8c, 0x01,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69,
	0x6e, 0x69, 0x74, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x65, 0x78, 0x69, 0x74, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69,
	0x64, 0x6c, 0x65, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6d, 0x6f,
	0x76, 0x65, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x74, 0x65, 0x6c,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x10, 0x07, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x6b, 0x67, 0x2e,
	0x43, 0x68, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x9e,
	0x01, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x05, 0x75, 0x6e, 0x69,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x1a, 0x43, 0x0a, 0x0a, 0x55, 0x6e,
	0x69, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x6b, 0x67, 0x2e,
	0x55, 0x6e, 0x69, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x2d, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12,
	0x1d, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x70, 0x6b, 0x67, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x48,
	0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x03,
	0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x6b, 0x67, 0x2e,
	0x50, 0x6f, 0x73, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0x28, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x45, 0x78, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x28, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x6c, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x56, 0x0a, 0x09,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x6b, 0x67, 0x2e,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x32, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x08, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x75, 0x70, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x64, 0x6f, 0x77, 0x6e, 0x10, 0x03, 0x42, 0x05, 0x5a, 0x03, 0x70, 0x6b, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_events_proto_rawDescOnce sync.Once
	file_pkg_events_proto_rawDescData = file_pkg_events_proto_rawDesc
)

func file_pkg_events_proto_rawDescGZIP() []byte {
	file_pkg_events_proto_rawDescOnce.Do(func() {
		file_pkg_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_events_proto_rawDescData)
	})
	return file_pkg_events_proto_rawDescData
}

var file_pkg_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_events_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_events_proto_goTypes = []any{
	(Direction)(0),        // 0: pkg.Direction
	(Event_Type)(0),       // 1: pkg.Event.Type
	(*Pos)(nil),           // 2: pkg.Pos
	(*Unit)(nil),          // 3: pkg.Unit
	(*CharInfo)(nil),      // 4: pkg.CharInfo
	(*Event)(nil),         // 5: pkg.Event
	(*UpdateInfo)(nil),    // 6: pkg.UpdateInfo
	(*EventInit)(nil),     // 7: pkg.EventInit
	(*EventConnect)(nil),  // 8: pkg.EventConnect
	(*EventTeleport)(nil), // 9: pkg.EventTeleport
	(*EventExit)(nil),     // 10: pkg.EventExit
	(*EventIdle)(nil),     // 11: pkg.EventIdle
	(*EventMove)(nil),     // 12: pkg.EventMove
	nil,                   // 13: pkg.EventInit.UnitsEntry
}
var file_pkg_events_proto_depIdxs = []int32{
	2,  // 0: pkg.Unit.pos:type_name -> pkg.Pos
	0,  // 1: pkg.Unit.direction:type_name -> pkg.Direction
	0,  // 2: pkg.Unit.side:type_name -> pkg.Direction
	4,  // 3: pkg.Unit.info:type_name -> pkg.CharInfo
	1,  // 4: pkg.Event.type:type_name -> pkg.Event.Type
	7,  // 5: pkg.Event.init:type_name -> pkg.EventInit
	8,  // 6: pkg.Event.connect:type_name -> pkg.EventConnect
	10, // 7: pkg.Event.exit:type_name -> pkg.EventExit
	11, // 8: pkg.Event.idle:type_name -> pkg.EventIdle
	12, // 9: pkg.Event.move:type_name -> pkg.EventMove
	9,  // 10: pkg.Event.teleport:type_name -> pkg.EventTeleport
	6,  // 11: pkg.Event.updateInfo:type_name -> pkg.UpdateInfo
	4,  // 12: pkg.UpdateInfo.info:type_name -> pkg.CharInfo
	13, // 13: pkg.EventInit.units:type_name -> pkg.EventInit.UnitsEntry
	3,  // 14: pkg.EventConnect.unit:type_name -> pkg.Unit
	2,  // 15: pkg.EventTeleport.pos:type_name -> pkg.Pos
	0,  // 16: pkg.EventMove.direction:type_name -> pkg.Direction
	3,  // 17: pkg.EventInit.UnitsEntry.value:type_name -> pkg.Unit
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_events_proto_init() }
func file_pkg_events_proto_init() {
	if File_pkg_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_events_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_events_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Unit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_events_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CharInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_events_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_events_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_events_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*EventInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_events_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EventConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_events_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*EventTeleport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_events_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*EventExit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_events_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*EventIdle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_events_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*EventMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_events_proto_msgTypes[3].OneofWrappers = []any{
		(*Event_Init)(nil),
		(*Event_Connect)(nil),
		(*Event_Exit)(nil),
		(*Event_Idle)(nil),
		(*Event_Move)(nil),
		(*Event_Teleport)(nil),
		(*Event_UpdateInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_events_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_events_proto_goTypes,
		DependencyIndexes: file_pkg_events_proto_depIdxs,
		EnumInfos:         file_pkg_events_proto_enumTypes,
		MessageInfos:      file_pkg_events_proto_msgTypes,
	}.Build()
	File_pkg_events_proto = out.File
	file_pkg_events_proto_rawDesc = nil
	file_pkg_events_proto_goTypes = nil
	file_pkg_events_proto_depIdxs = nil
}
